//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyGim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class socios
    {
        public int id_socio { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public string dni { get; set; }
        public string telefono { get; set; }
        public string correo { get; set; }
        public string direccion { get; set; }
        public string sexo { get; set; }
        public Nullable<System.DateTime> fecha_nac { get; set; }
        public string descripcion { get; set; }
        public Nullable<int> nro_cuenta { get; set; }
        public Nullable<int> id_usuario { get; set; }
    
        public virtual cta_cte cta_cte { get; set; }
        public virtual rutinas rutinas { get; set; }
        public virtual usuarios usuarios { get; set; }
    }
}
